name: push event
on: 
  push:
    branches: kishore_Test_branch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -a

      - uses: actions/checkout@v4
    
      - name: List files after checkout
        run: ls -a    
  
   
