name: MainBranch-event

on:
  push:
    branches:
      - main
    paths:
      - README.md

  pull_request:
    types:
      - closed
      - opened
      - reopened
    branches:
      - main

  issues:
    types:
      - opened
      - closed
    branches:
      - main

  schedule:
    - cron: "*/2 * * * *"

  workflow_dispatch:

jobs:
  job2:
    name: Job 2 - Pull Request Task
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: List files before checkout
        run: ls -a

      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files after checkout
        run: ls -a

      - name: Run Job 2 Task
        run: echo "Job 2 is triggered by pull request"

  job1:
    name: Job 1 - Is dependent on job 2
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Run job1 Task
        run: echo "Job 1 ran because Job 2 completed"
