name: MainBranch-event

on:
  push:
    branches:
      - main
    paths:
      - README.md

  pull_request:
    types:
      - closed
      - opened
      - reopened
    branches:
      - main

  issues:
    types:
      - opened
      - closed
    branches:
      - main

  workflow_dispatch:

jobs:
  job2:
    name: Job 2 - Pull Request Task
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: List files before checkout
        run: ls -a

      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files after checkout
        run: ls -a

      - name: Run Job 2 Task
        run: echo "Job 2 is triggered by pull request"

  job1:
    name: Job 1 - Is dependent on job 2
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Run job1 Task
        run: echo "Job 1 ran because Job 2 completed"
  job3:
    name: job 3 is dependent on job 1
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: List working directory
        run: |
          pwd
      - name: Run job 3
        run: echo "job 3 is running because job 1 is completed"            

        
