name: My matrix

on: workflow_call   

jobs:
  matrix-test:
    name: Test matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Check default Python version   
        run: python --version

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Confirm Python version   
        run: python --version
